### PR TITLE
feat: release 4.0.0

### PR DESCRIPTION
**Pull request by ZurabDev**
### Bug fixes
- fix(doc/input-date-time): set static default time
- fix(chore): stackblitz import style error #1209 #1410
@alexhawkins94 for check
https://stackblitz.com/edit/prizm-v3-demo-s2pfqz?file=src%2Fapp%2Fapp.component.ts
- fix(components/date-time): time validation does not always affect control display #1419
- fix(doc): when a hint appears, some storefront elements change theme #1407
- fix(doc/input-date-multi): update currentIdx on changes on api page
- fix(components/checkbox): removed unnecessary right margin for label-less checkboxes 
- fix(components/table): added hover and focus styles for cells containing `prizmInput` and `prizmInputLayout`
- fix(components/panel): adjusted margins in `PrizmPanel` component 
- fix(components/inputs): layout update for Input Chips eliminates the need for additional margins 
- fix(components/inputs): removed default label from PrizmSelectOptions and PrizmMultiSelectOptions 
- fix(components/file-upload): `PrizmFileUploadOptions` interface updated, status names to be added via translations 
- fix(components/file-upload): added fields for file upload status translations in `PrizmLanguageFileUpload` 
- fix(i18n): added `search` field to `PrizmLanguageKit` for InputSelect and InputMultiSelect search translations 
- fix(components/input-date-time-range): afte clear time values in calendar got error #1368
- fix(components/input-date-time): min/max does not work correctly in InputLayoutDateTime #1421

### Features
- feat: i18n support for base input text of validation #1354 #1402
- feat(ci): new action to deploy doc for angular with 17 version
- feat(components/hint): add passing context as $implicit to templates #291
- feat(components/tooltip): add passing context as $implicit to templates #291
- feat(components/table): discuss extending hover and focus styles to other controls 
- feat(i18n): enhanced search translation support for InputSelect and InputMultiSelect 

#### Removed components
- `input-date-time`
- `input-date-time-range`
- `input-time`
- `input-date`
- `input-month`
- `input-month-range`
- `input-date-range`
- `input-date-relative`
- `select`
- `multi-select`
- `carousel`
     
These components will no longer be supported and a replacement must be found to find alternative components with input-layout.

#### Theme
- Legacy color tokens (v1, v2) have been completely removed. Mapping for new colors will be provided where possible. Colors without direct analogues in the new color scheme will require manual redefinition in projects.
- Tokens with the prizm-v3 prefix have been replaced with prizm-

#### Icons
The `prizm-icon` component has been removed. Instead, a new set of icons has been introduced in the `prizm-icons` component, where the icons have new names. For each of the old icons, alternative names are provided. You can find a complete table of correspondence between old and new icon names at the link: https://prizm.site/components/icons/Old_Icons.

The following components used the legacy icon component:
- accordion
- table
- breadcrumbs
- tabs
- button
- icon-button
- split-button
- primitive-spin-button
- primitive-year-month-pagination
- calendar-range
- column-settings
- toggle
- input-select
- input-multi-select
-file-upload
- navigation-menu
- indicator
- input-icon-button
- dropdown-host
- tree
- stepper
- checkbox
- tooltip
-paginator

This means that when using the above components in your projects, you will need to either manually update the icon names to new ones, or use our service, which will automatically update the icon names to their new versions. Instructions for using this service are available at: https://prizm.site/components/icons#migrate-from-old-name.

### CODE REVIEW

**Review by alexhawkins94 — COMMENTED** [review]
v4

Table
Поправить отступ между иконкой фильтрации и заголовком столбца 
image

было
image

**Review by alexhawkins94 — COMMENTED** [review]
Table
Иконки для сортировки используются 24х24, раньше были 16х16.
Возможно, стоит уточнить у дизайенра.
chrome_ZUrG570P1L

было
chrome_1v5yaYs884

**Review by alexhawkins94 — COMMENTED** [review]
v4
InputDateTimeRange
В Live demo наблюдаю ряд проблем. 

-Открыть дропдаун 
-Очистить время для начала и конца
-Сделать клик вне инпута для закрытия дропдауна
ФР: возникает ошибка to string error после закрытия дропдауна
image

**Review by alexhawkins94 — COMMENTED** [review]
InputDateTimeRange
В Live demo наблюдаю ряд проблем. 

2. Предлагаю решить эту проблему https://github.com/zyfra/Prizm/issues/1388 в live demo

**Review by alexhawkins94 — COMMENTED** [review]
v3 v4

InputDateTimeRange
В Live demo наблюдаю ряд проблем. 

3.вручную введенное с клавиатуры время не прокидывается в value.
При вводе времени оно приводится к 00:00

**Review by alexhawkins94 — COMMENTED** [review]
v4

Table
Editable row
Ширина дропдауна Уже чем родительский инпут
Раньше в v3 ширина дропдауна была практически идентична ширине родительского инпута.
Выглядит очень ужасно, так как если добавить к таблицам вертикальные границы то ui станет выглядеть очень перегруженно.
Возможно связано с использованием listItem ?
chrome_AzY7F1i2bJ

Было
chrome_gSBdaVOGeT

**Review by alexhawkins94 — COMMENTED** [review]
v3 v4

InputMonthRange
при position=center, наличии индикатора и кнопка очистки содержимое инпута пересекается с контролами
chrome_wCs4vaeuj5

**Review by alexhawkins94 — COMMENTED** [review]
v3 v4

Position=center не меняет положение содержимого в ряде дейтпикеров
dateRange
dateTime
dateTimeRange

а также в:
multiselect

если в этих компонентах это свойство не должно работать/не нужно - следует убрать его

**Review by alexhawkins94 — COMMENTED** [review]
v4

InputDateRelative
В дропдауне с компонентами формулы иконки стали не информативные и вводят заблуждение.
Например, иконка для обозначения текущих суток сейчас содержит в себе букву t (маленькая Т), что неправильно - при ручном вводе формулы использование буквы t приводит к срабатыванию валидации. Аналогично для иконки "Год", "Месяц"
сейчас используется "y" и "mo" (что вводит в заблуждение при ручном вводе, т.к. мы не поддерживаем такие символы), раньше было "Y", "M"

Необходимо использовать информативные иконки
image

было:
XgADcZyQz0

**Review by alexhawkins94 — COMMENTED** [review]
v4

Input Select, live demo - не отображается выбранная иконка
-выбрать иконку в свойстве icon
ФР: иконка не отображается в инпуте

chrome_5euhtlJ5i2

было 
image

**Review by alexhawkins94 — COMMENTED** [review]
v3 v4

InputSelect
При выбранном значении valueTemplate + position=center иконка отображается по левой стороны инпута.

image

**Review by alexhawkins94 — COMMENTED** [review]
v3 v4 

InputSelect
Некорректный цвет плейсхолдера в инпуте если задан ValueTemplate. 

image

Если ValueTemplate не задан, то placeholder имеет правильный цвет шрифта --prizm-text-icon-disable.
chrome_2ruzxDXEmP

**Review by alexhawkins94 — COMMENTED** [review]
v3 v4

TextArea, при position=center, inner=true и наличии статуса и индикатора кнопка очистки и индикатор не выравнены по краю
image

**Review by alexhawkins94 — COMMENTED** [review]
v3 v4

Carousel, live demo - есть возможность привести пример в нерабочее состояние.
-установить forcClear=true
-очистить инпут в карусели
-переключить значение
ФР: инпут очищен. дальнейшее взаимодействие с примером в live demo невозможно, значение не переключается, возможности ввода нет
ОР: forceClear и отображение кнопки очистки должен работать только если в карусели есть возможность ручного ввода (input as carousel)

chrome_nPNWxEiTvo

**Review by alexhawkins94 — COMMENTED** [review]
v4 

Checkbox
Новая иконка в  чекбоксе неудобна для восприятия - слишком блеклая и не заметная, линия сликом тонкая. 
Старая реализация с толстой линией гораздо удобнее для визуального восприятия.

сейчас
chrome_170rPmInmG

было
chrome_EDfDe0THEw

**Review by alexhawkins94 — COMMENTED** [review]
v4

Table
Шевроны для групп (раскрыть\свернуть группу) используются 24х24, раньше использовались 16х16
image

раньше
image

**Review by alexhawkins94 — COMMENTED** [review]
v3 v4 

Tabs - большой отступ перед иконкой-кнопкой закрытия таба. padding 16 + margin 8. Уточнить у дизайнеров.

Как результат, таб выглядит раздутым и содержит разные отступы внутри между текст+каунтер, каунтер+кнопка закрытия
chrome_uQkdKtW4qc

chrome_lNChvNH3OJ

chrome_QL0c7ohT9R

**Review by alexhawkins94 — COMMENTED** [review]
v3 v4

Tabs. Contained tabs.
При одновременном состоянии фокуса и ховера на contained tab происходит обрезка правой границы у фокуса
image

**Review by alexhawkins94 — COMMENTED** [review]
v4

Tree
Не отображается часть иконок в примере Component, Padding indent

сейчас
image


было
image

**Review by alexhawkins94 — COMMENTED** [review]
v4

Toast
Кнопка закрытия поменяла свое расположение, теперь она находится по середине тоста - применительно ко всем примерам 

Сейчас:
chrome_sfpt6rLHSs

Было:
chrome_f4QOkSnPfX

**Review by alexhawkins94 — COMMENTED** [review]
v4

Listing item, пример with instruments - не отображается часть иконок в компоненте.
image

**Review by alexhawkins94 — COMMENTED** [review]
v4

Dialog, Sidebar - при переходе в live demo ошибка max call stack exceeded, содержимое странички не отображается
chrome_C4jjc9GhBk

**Review by alexhawkins94 — COMMENTED** [review]
v4 

Colors
На страничке в разделе Guidelines > Colors в темной теме неправильный цвет шрифта, из-за чего текст нечитаем/почти невидим. 
Кажется, мы чинили это при разработке в4, возможно потерялось/потерлось при мержах/обновлении тайги? 

chrome_7BoltIKK38

**Comment by ickisIckis** [comment]
> v4
> 
> Colors На страничке в разделе Guidelines > Colors в темной теме неправильный цвет шрифта, из-за чего текст нечитаем/почти невидим. Кажется, мы чинили это при разработке в4, возможно потерялось/потерлось при мержах/обновлении тайги?
> 
> chrome_7BoltIKK38


Если не чинили отдельно на этой неделе, то это issue 900 из 3.12.0, под четверку пока не было сделано:
https://github.com/zyfra/Prizm/pull/1401

**Review by alexhawkins94 — COMMENTED** [review]
v4

поправить по-возможности тайговский ховер в главном меню, сейчас цвет ховера сливается с заголовком айтема меню.
Появилось после обновления
image

**Review by alexhawkins94 — COMMENTED** [review]
v3 v4

Buttons, icon buttons
В live demo у кнопок нет ховера/фокуса/pressed состояний

**Review by alexhawkins94 — APPROVED** [review]

**Pull request merged**
