### PR TITLE
feat(chore): pre release to 5.0.0 #000

### PR DESCRIPTION
**Pull request by ZurabDev**
### Release Notes - Major Update for Prizm Libraries

_We are excited to announce a major update for Prizm libraries! This release includes a significant number of changes, including the removal of deprecated modules and functions, as well as the introduction of standalone components and directives._

#### Breaking Changes

1. **Module Removals and Standalone Replacements:**
   - **PrizmCounterModule**: Removed. Use standalone.
   - **PrizmButtonModule**: Removed. Use standalone.
   - **PrizmCheckedModule**: Removed. Use standalone `PrizmCheckedDirective`.
   - **PrizmAutoResizeModule**: Removed. Use standalone `PrizmAutoResizeDirective`.
   - **PrizmAutoFocusModule**: Removed. Use standalone `PrizmAutoFocusDirective`.
   - **PrizmStopPropagationModule**: Removed. Use standalone `PrizmStopPropagationDirective`.
   - **PrizmZoneEventModule**: Removed. Use standalone `PrizmZoneEventDirective`.
   - **PrizmCalendarSheetModule**: Removed. Use standalone `PrizmCalendarSheetPipe`.
   - **PrizmMapperModule**: Removed. Use standalone `PrizmMapperPipe`.
   - **PrizmMonthModule**: Removed. Use standalone `PrizmMonthPipe`.
   - **PrizmChartsAreaModule**: Removed. Use standalone `PrizmChartsAreaComponent`.
   - **PrizmChartsBarModule**: Removed. Use standalone `PrizmChartsBarComponent`.
   - **PrizmChartsColumnModule**: Removed. Use standalone `PrizmChartsColumnComponent`.
   - **PrizmChartsGaugeModule**: Removed. Use standalone `PrizmChartsGaugeComponent`.
   - **PrizmChartsLineModule**: Removed. Use standalone `PrizmChartsLineComponent`.
   - **PrizmChartsPieModule**: Removed. Use standalone `PrizmChartsPieComponent`.
   - **PrizmChartsRadarModule**: Removed. Use standalone `PrizmChartsRadarComponent`.
   - **PrizmChartsRadialBarModule**: Removed. Use standalone `PrizmChartsRadialBarComponent`.
   - **PrizmChartsScatterModule**: Removed. Use standalone `PrizmChartsScatterComponent`.
   - **PrizmChartsTreemapModule**: Removed. Use standalone `PrizmChartsTreemapComponent`.
   - **PrizmChartsWaterfallModule**: Removed. Use standalone `PrizmChartsWaterfallComponent`.
   - **PrizmPanelModule**: Removed. Use standalone `PrizmPanelComponent`.
   - **PrizmPrimitiveCalendarRangeModule**: Removed. Use standalone `PrizmPrimitiveCalendarRangeComponent`.
   - **PrizmPrimitiveSpinButtonModule**: Removed. Use standalone `PrizmPrimitiveSpinButtonComponent`.
   - **PrizmInputCorrectorModule**: Removed. Use standalone `PrizmInputCorrectorDirective`.
   - **PrizmInputHintModule**: Removed. Use standalone `PrizmInputHintDirective`.
   - **PrizmInputAllowedSymbolsModule**: Removed. Use standalone `PrizmInputAllowedSymbolsDirective`.
   - **PrizmErrorPageModule**: Removed. Use standalone `PrizmErrorPageComponent`.

2. **Deprecated Modules and Functions Removed:**
   - **PrizmFlagIconsModule**
   - **CallFuncPipe** (use `PrizmCallFuncPipe`)
   - **PrizmCallFuncModule**
   - **PrizmPluckModule**
   - **PrizmToObservableModule**
   - **PrizmToTypeModule**
   - **PrizmOverlayModule**
   - **ToTypePipe**
   - **PrizmLetModule**
   - **prizmCreateTimeMask**, **prizmCreateTimePartMask**
   - **prizmExtractI18n**
   - **PRIZM_DATE_RANGE_FILLER**, **PRIZM_DATE_FILLER** (tokens)
   - **PrizmBaseColor**, **PrizmSupportColor** (enums)
   - **PrizmSkeletonModule**
   - **PrizmWrapperModule**
   - **PrizmScrollIntoViewModule**
   - **PrizmRepeatTimesModule**
   - **PrizmPreventDefaultModule**
   - **PrizmPressedModule**
   - **PrizmOverscrollModule**
   - **PrizmInputNativeValueModule**
   - **PrizmMutationObserveModule**
   - **PrizmLifecycleModule**
   - **PrizmHoveredModule**
   - **PrizmFocusedModule**
   - **PrizmFocusableModule**
   - **PrizmFocusTrapModule**
   - **PrizmDropdownZoneModule**
   - **PrizmDroppableModule**
   - **PrizmElementReadyModule**
   - **PrizmDropdownControllerModule**
   - **PrizmIconsSvgModule**
   - **PrizmShadowModule**
   - **PrizmWidgetModule**
   - **PrizmTreeButtonModule**
   - **PrizmToggleModule**
   - **PrizmSwitcherModule**
   - **PrizmSpinnerModule**
   - **PrizmRadioButtonModule**
   - **PrizmPaginatorModule**
   - **PrizmLoaderModule**
   - **PrizmLinkModule**
   - **PrizmPrimitiveCalendarModule**
   - **PrizmPrimitiveMonthPickerModule**
   - **PrizmPrimitiveYearMonthPaginationModule**
   - **PrizmPrimitiveYearPickerModule**
   - **PrizmCardModule**
   - **PrizmHintModule**
   - **PrizmScrollControlsModule**
   - **PrizmInputIconButtonModule**
   - **PrizmInputDateMultiModule**
   - **PrizmIndicatorModule**
   - **PrizmDialogModule**
   - **PrizmDialogConfirmModule**
   - **PrizmCronHumanReadableModule**
   - **PrizmFileUploadModule**
   - **PrizmCalendarMonthModule**
   - **PrizmCalendarRangeModule**
   - **PrizmSidebarModule**
   - **PrizmColumnSettingsModule**

3. **Renamed Components:**
   - **PanelComponent** renamed to `PrizmPanelComponent`.

4. **Spelling Corrections in Exports:**
   - **PrizmSelectValueTransformver** corrected to `PrizmSelectValueTransformer`.
   - **GridItemComponent** corrected to `PrizmGridItemComponent`.
   - **GridComponent** corrected to `PrizmGridComponent`.
   - **IndicatorComponent** corrected to `PrizmIndicatorComponent`.
   - **SwitcherItemComponent** corrected to `PrizmSwitcherItemComponent`.

#### Fixes and Features

- **fix(components/chips)**: Corrected spelling error in CSS variable name for `--prizm-chips-item-height`.
- **feat(components)**: Removed deprecated function `prizmCreateDateMask`.
- **feat(components)**: Removed deprecated exports with spelling mistakes: `PrizmSelectValueTransformver`, `GridItemComponent`, `GridComponent`, `IndicatorComponent`, `SwitcherItemComponent`, `CallFuncPipe`, `ToTypePipe`.

### CODE REVIEW

**Review by ickisIckis — COMMENTED** [review]
Обновим чек-лист для пятерки?  В формате v4 + v5?

**Comment by ZurabDev** [comment]
> Обновим чек-лист для пятерки? В формате v4 + v5?

Это сделаем до выхода основной версии, надо проверить что понять каким будет чеклист

**Review by ickisIckis — COMMENTED** [review]
package-lock должен быть в mr?

**Comment by ZurabDev** [comment]
> package-lock должен быть в mr?

Да

**Review by alexhawkins94 — APPROVED** [review]

**Pull request closed without merging**
