### PR TITLE
4.7.0

### PR DESCRIPTION
**Pull request by ZurabDev**
### Features

- feat(components/theme): prefer global theme if did not passed any value #1426
- feat(components/input-select): hide chevron when disabled #1917
- feat(doc): update information about us #2143
- feat(doc/dropdown-host): updated example select panel added custom vars for overlay #2135
- feat(components/droprodown-trigger-click): new directive to trigger dropdown host and fix bug #1850 #2124

### Bugfixes

- fix(components/table): use proxy to update context #1506 #1845
- fix(components/navigation-menu): padding changed from 4px to 8px between text and other el #1633
- fix(components/input-control): on each update value emits two times #2087
- fix(chore): fix version in schematics #1987
- fix(components/multi-select): hint did not show after search #1980
- fix(components/input-select): hide chevron when disabled #1917
- fix(components/input-multiselect): hide chevron when disabled #1917
- fix(components/input-tree-multiselect): hide chevron when disabled #1917
- fix(components/input-multiselect): chips and chevron should be inactive when disabled #1914
- fix(components/tabs): correct focus styles for contained tabs #1729
- fix(components/input): padding changed for inner inputs #1763
- fix(components/input-layout): correct icon for danger status #1916
- fix(components/navigation): register icons for navigation header and example #1836
- fix(components/switcher): switcher button markup correction #2032
- fix(components/button): fixed problem with confused test id for buttons with and without icons #2150

### CODE REVIEW

**Review by ickisIckis — APPROVED** [review]
LGTM

**Comment by alexhawkins94** [comment]
На странице "О дизайн системе" осталось старое описание
image

описание из 5:
chrome_PQ5TFxH8iy

**Comment by alexhawkins94** [comment]
@ZurabDev фикс touched для carousel из 5.2 заливать будем?

**Comment by alexhawkins94** [comment]
chechbox
ошибка в live demo чекбокса - Element: index Selector:prizm-checkbox has not api for inputs or outputs
Inputs: readonly
image

**Comment by alexhawkins94** [comment]
button, icon button  - live demo
не отображается ховер у кнопок. событие эмитится, но визуальных изменений нет

**Comment by alexhawkins94** [comment]
inputTreeMultiSelect
чипс выходит за границу инпута 
chrome_gAZrR45RGs

так же в мультиселекте наблюдаю старую логику добавления айтемов в чипсы, отличную от 5.2

**Comment by alexhawkins94** [comment]
multiselect, tree multiselect - focusable через tab при disabled=true
chrome_EnfJlWFGI3
chrome_DnhNyXBDIj

**Review by alexhawkins94 — APPROVED** [review]

**Pull request merged**
